// Get the content of a meta tag with http-equiv="Content-Language" and name="eng"

let userLanguage = document.querySelector('meta[http-equiv="Content-Language"]').getAttribute("name");
console.log(userLanguage);
	
function translate(text, language) {
        const translations = {
	en: {
		"Commercial Loan Application Form": "Commercial Loan Application Form",
		"Applicant Information": "Applicant Information",
		"Name": "Name",
		"First Name": "First Name",
		"Last Name": "Last Name",
		"Address*": "Address*",
		"Street Address": "Street Address",
		"Street Address Line 2": "Street Address Line 2",
		"City": "City",
		"State / Province": "State / Province",
		"Postal / Zip Code": "Postal / Zip Code",
		"Applicant Status*": "Applicant Status*",
		"New Client": "New Client",
		"Existing Client": "Existing Client",
		"Other": "Other",
		"Job / Occupation": "Job / Occupation",
		"Job Classification": "Job Classification",
		"Please Select": "Please Select",
		"Email Address": "Email Address",
		"example@example.com": "example@example.com",
		"Loan Information": "Loan Information",
		"Loan Amount*": "Loan Amount*",
		"Loan/Credit Term*": "Loan/Credit Term*",
		"Type of Loan Facility*": "Type of Loan Facility*",
		"Overdraft": "Overdraft",
		"Commercial Property": "Commercial Property",
		"Industrial Property": "Industrial Property",
		"Micro Loans": "Micro Loans",
		"Revolving Credit": "Revolving Credit",
		"Equipment Financing": "Equipment Financing",
		"Other": "Other",
		"Purpose of your Loan*": "Purpose of your Loan*",
		"ID card front*": "ID card front*",
		"Browse Files": "Browse Files",
		"No file chosen": "No file chosen",
		"ID card back*": "ID card back*",
		"I/We hereby affirm this application for loan or credit as specified above in this application form, on behalf of the business applicant. The information specified above provided are true and correct to the best of my/our knowledge and with no intention to commit acts of misrepresentation. No addition or omission has been made which may lead to acts of fraud or any form of impropriety.": "I/We hereby affirm this application for loan or credit as specified above in this application form, on behalf of the business applicant. The information specified above provided are true and correct to the best of my/our knowledge and with no intention to commit acts of misrepresentation. No addition or omission has been made which may lead to acts of fraud or any form of impropriety.",
		"This field is required.": "This field is required.",
		"I/We agree that the Lender is authorized to conduct any form of investigation in order to verify and confirm our declarations and requests, including, but not limited to conduct any investigation of my/our credit standing.": "I/We agree that the Lender is authorized to conduct any form of investigation in order to verify and confirm our declarations and requests, including, but not limited to conduct any investigation of my/our credit standing.",
		"Signature": "Signature"
	},
	pl: {
		"Commercial Loan Application Form": "Formularz Wniosku o Kredyt Handlowy",
		"Applicant Information": "Informacje o Wnioskodawcy",
		"Name": "Imię",
		"First Name": "Imię",
		"Last Name": "Nazwisko",
		"Address*": "Adres*",
		"Street Address": "Adres ulicy",
		"Street Address Line 2": "Adres ulicy, część 2",
		"City": "Miasto",
		"State / Province": "Województwo",
		"Postal / Zip Code": "Kod pocztowy",
		"Applicant Status*": "Status Wnioskodawcy*",
		"New Client": "Nowy Klient",
		"Existing Client": "Istniejący Klient",
		"Other": "Inny",
		"Job / Occupation": "Praca / Zawód",
		"Job Classification": "Klasyfikacja Zawodu",
		"Please Select": "Proszę Wybrać",
		"Email Address": "Adres Email",
		"example@example.com": "przyklad@przyklad.com",
		"Loan Information": "Informacje o Pożyczce",
		"Loan Amount*": "Kwota Pożyczki*",
		"Loan/Credit Term*": "Okres Pożyczki/Kredytu*",
		"Type of Loan Facility*": "Rodzaj Udogodnienia Kredytowego*",
		"Overdraft": "Debet",
		"Commercial Property": "Nieruchomość Handlowa",
		"Industrial Property": "Nieruchomość Przemysłowa",
		"Micro Loans": "Mikropożyczki",
		"Revolving Credit": "Kredyt Obracający się",
		"Equipment Financing": "Finansowanie Sprzętu",
		"Other": "Inny",
		"Purpose of your Loan*": "Cel Twojej Pożyczki*",
		"ID card front*": "Przód dowodu osobistego*",
		"Browse Files": "Przeglądaj Pliki",
		"No file chosen": "Brak wybranego pliku",
		"ID card back*": "Tył dowodu osobistego*",
		"I/We hereby affirm this application for loan or credit as specified above in this application form, on behalf of the business applicant. The information specified above provided are true and correct to the best of my/our knowledge and with no intention to commit acts of misrepresentation. No addition or omission has been made which may lead to acts of fraud or any form of impropriety.": "Oświadczam, że niniejszy wniosek o pożyczkę lub kredyt został złożony w imieniu przedsiębiorcy. Podane powyżej informacje są prawdziwe i poprawne według mojej/naszej najlepszej wiedzy, bez zamiaru popełnienia czynów wprowadzenia w błąd. Nie dokonano dodatków ani pominięć, które mogłyby prowadzić do działań oszukańczych lub jakiejkolwiek formy nieprawidłowości.",
		"This field is required.": "To pole jest wymagane.",
		"I/We agree that the Lender is authorized to conduct any form of investigation in order to verify and confirm our declarations and requests, including, but not limited to conduct any investigation of my/our credit standing.": "Zgadzam się, że Pożyczkodawca ma uprawnienie do przeprowadzenia wszelkich form badań w celu zweryfikowania i potwierdzenia naszych oświadczeń i wniosków, w tym, ale nie tylko, badania mojej/naszej zdolności kredytowej. Pod warunkiem, że po otrzymaniu powiadomienia Pożyczkodawca może ujawnić informacje finansowe dotyczące naszego konta innemu pożyczkodawcy lub zainteresowanej stronie, której może być potrzebne do ujawnienia w związku z dochodzeniem kredytowym.",
		"Provided that with given notice, Lender may disclose financial information of our account to any another lender or parties interested to the information which may be needed for disclosure in relevance to credit investigation.": "Pod warunkiem, że przy udzielonym zawiadomieniu, Kredytodawca może ujawnić informacje finansowe naszego konta każdemu innemu kredytodawcy lub zainteresowanej stronie, co może być konieczne do ujawnienia w związku z dochodzeniem kredytowym.",
		"Signature": "Podpis",
		"Proprietor": "Propriétaire",
	    "Partnership": "Partenariat",
	    "Corporation": "Société anonyme",
	    "Non-profit": "Organisme à but non lucratif",
	    "Organization": "Organisation",
	    "Government": "Gouvernement",
	    "1 year": "1 an", 
	    "2 years": "2 ans",
	    "3 years": "3 ans",
	    "4 years": "4 ans",
	    "5 years": "5 ans",
	    "6 years": "6 ans",
	    "7 years": "7 ans",
	    "8 years": "8 ans",
	    "9 years": "9 ans",
	    "10 years": "10 ans",
	     "Date Signed*": "Data podpisania*",
	    "Client existant": "Istniejący klient",
	    "New Client": "Nowy klient",
	    "Other": "Inny",
	     "Application Received": "Otrzymano wniosek",
    "We received your loan application request;": "Otrzymaliśmy Twoje zgłoszenie wniosku o pożyczkę;",
    "we'll be in touch shortly!": "wkrótce się skontaktujemy!"
	},
	fr: { 
		"Commercial Loan Application Form": "Formulaire de demande de prêt commercial",
		"Applicant Information": "Informations sur le demandeur",
		"Name": "Nom",
		"First Name": "Prénom",
		"Last Name": "Nom de famille",
		"Address*": "Adresse*",
		"Street Address": "Adresse",
		"Street Address Line 2": "Adresse ligne 2",
		"City": "Ville",
		"State / Province": "État / Province",
		"Postal / Zip Code": "Code postal / ZIP",
		"Applicant Status*": "Statut du demandeur*",
		"New Client": "Nouveau client",
		"Existing Client": "Client existant",
		"Other": "Autre",
		"Job / Occupation": "Emploi / Occupation",
		"Job Classification": "Classification de l'emploi",
		"Please Select": "Veuillez sélectionner",
		"Email Address": "Adresse e-mail",
		"example@example.com": "exemple@exemple.com",
		"Loan Information": "Informations sur le prêt",
		"Loan Amount*": "Montant du prêt*",
		"Loan/Credit Term*": "Durée du prêt/crédit*",
		"Type of Loan Facility*": "Type de facilité de prêt*",
		"Overdraft": "Découvert",
		"Commercial Property": "Bien commercial",
		"Industrial Property": "Bien industriel",
		"Micro Loans": "Micro-prêts",
		"Revolving Credit": "Crédit renouvelable",
		"Equipment Financing": "Financement d'équipement",
		"Other": "Autre",
		"Purpose of your Loan*": "But de votre prêt*",
		"ID card front*": "Carte d'identité (recto)*",
		"Browse Files": "Parcourir les fichiers",
		"No file chosen": "Aucun fichier sélectionné",
		"ID card back*": "Carte d'identité (verso)*",
		"I/We hereby affirm this application for loan or credit as specified above in this application form, on behalf of the business applicant. The information specified above provided are true and correct to the best of my/our knowledge and with no intention to commit acts of misrepresentation. No addition or omission has been made which may lead to acts of fraud or any form of impropriety.": "Par la présente, je/nous affirmons cette demande de prêt ou de crédit telle que spécifiée ci-dessus dans ce formulaire de demande, au nom du demandeur commercial. Les informations spécifiées ci-dessus sont vraies et correctes selon ma/notre connaissance et sans intention de commettre",
		"This field is required.": "Ce champ est obligatoire.",
		"I/We agree that the Lender is authorized to conduct any form of investigation in order to verify and confirm our declarations and requests, including, but not limited to conduct any investigation of my/our credit standing.": "Je/nous convenons que le prêteur est autorisé à effectuer toute forme d'enquête afin de vérifier et confirmer nos déclarations et demandes, y compris, mais sans s'y limiter, toute enquête sur ma/notre solvabilité. À condition d'un préavis donné, le prêteur peut divulguer des informations financières de notre compte à tout autre prêteur ou partie intéressée par les informations nécessaires à la divulgation en relation avec l'enquête de crédit.",
		"Provided that with given notice, Lender may disclose financial information of our account to any another lender or parties interested to the information which may be needed for disclosure in relevance to credit investigation.": "À condition qu'avec un préavis donné, le prêteur peut divulguer des informations financières de notre compte à tout autre prêteur ou parties intéressées par les informations qui peuvent être nécessaires pour la divulgation en rapport avec une enquête de crédit.",
		"Signature": "Signature",
		"proprietor": "właściciel",
	    "Partnership": "spółka",
	    "Corporation": "korporacja",
	    "Non-profit": "organizacja non-profit",
	    "Organization": "organizacja",
	    "Government": "rząd",
	    "1 year": "1 rok",
	    "2 years": "2 lata",
	    "3 years": "3 lata",
	    "4 years": "4 lata",
	    "5 years": "5 lat",
	    "6 years": "6 lat",
	    "7 years": "7 lat",
	    "8 years": "8 lat",
	    "9 years": "9 lat",
	    "10 years": "10 lat",
	    "Date Signed*": "Date de signature*",
	    "Client existant": "Client existant",
	    "New Client": "Nouveau client",
	    "Other": "Autre",
	    "Submit": "Soumettre",
	    "Clear Signature": "Signature claire",
	    "Application Received": "Demande reçue",
    "We received your loan application request;": "Nous avons bien reçu votre demande de prêt ;",
    "we'll be in touch shortly!": "nous vous contacterons sous peu !"
	},
	
  da: {
    "Commercial Loan Application Form": "Erhvervslån Ansøgningsskema",
    "Applicant Information": "Ansøgerinformation",
    "Name": "Navn",
    "First Name": "Fornavn",
    "Last Name": "Efternavn",
    "Address*": "Adresse*",
    "Street Address": "Vejadresse",
    "Street Address Line 2": "Vejadresse Linje 2",
    "City": "By",
    "State / Province": "Stat / Region",
    "Postal / Zip Code": "Postnummer / ZIP-kode",
    "Applicant Status*": "Ansøgerstatus*",
    "New Client": "Ny Kunde",
    "Existing Client": "Eksisterende Kunde",
    "Other": "Andet",
    "Job / Occupation": "Job / Beskæftigelse",
    "Job Classification": "Jobklassifikation",
    "Please Select": "Vælg venligst",
    "Email Address": "E-mailadresse",
    "example@example.com": "eksempel@eksempel.com",
    "Loan Information": "Låneoplysninger",
    "Loan Amount*": "Lånebeløb*",
    "Loan/Credit Term*": "Lån/Kreditperiode*",
    "Type of Loan Facility*": "Type af Lånefacilitet*",
    "Overdraft": "Overtræk",
    "Commercial Property": "Erhvervsejendom",
    "Industrial Property": "Industriejendom",
    "Micro Loans": "Mikrolån",
    "Revolving Credit": "Roterende Kredit",
    "Equipment Financing": "Udstyrsfinansiering",
    "Other": "Andet",
    "Purpose of your Loan*": "Formålet med dit Lån*",
    "ID card front*": "ID-kort forside*",
    "Browse Files": "Gennemse Filer",
    "No file chosen": "Ingen fil valgt",
    "ID card back*": "ID-kort bagside*",
    "I/We hereby affirm this application for loan or credit as specified above in this application form, on behalf of the business applicant. The information specified above provided are true and correct to the best of my/our knowledge and with no intention to commit acts of misrepresentation. No addition or omission has been made which may lead to acts of fraud or any form of impropriety.": "Jeg/Vi bekræfter hermed denne ansøgning om lån eller kredit som angivet ovenfor i denne ansøgningsformular, på vegne af forretningsansøgeren. De angivne oplysninger er sande og korrekte efter bedste viden og uden hensigt at begå handlinger af vildledning. Der er ikke foretaget tilføjelser eller udeladelser, der kan føre til handlinger af svig eller enhver form for uregelmæssighed.",
    "This field is required.": "Dette felt er påkrævet.",
    "I/We agree that the Lender is authorized to conduct any form of investigation in order to verify and confirm our declarations and requests, including, but not limited to conduct any investigation of my/our credit standing.": "Jeg/Vi er enige om, at långiveren er bemyndiget til at foretage enhver form for undersøgelse for at verificere og bekræfte vores erklæringer og anmodninger, herunder, men ikke begrænset til at foretage undersøgelse af min/vores kreditvurdering. Forudsat med forudgående varsel kan långiveren offentliggøre finansielle oplysninger om vores konto til en anden långiver eller parter interesseret i oplysningerne, som kan være nødvendige for offentliggørelse i forbindelse med kreditundersøgelsen.",
    "Provided that with given notice, Lender may disclose financial information of our account to any another lender or parties interested to the information which may be needed for disclosure in relevance to credit investigation.": "Forudsat at meddelelse gives, kan Långiver videregive finansielle oplysninger om vores konto til enhver anden långiver eller parter interesserede i oplysningerne, som kan være nødvendige for offentliggørelse i forbindelse med kreditundersøgelse.",
    "Signature": "Underskrift",
    "Proprietor": "ejer",
    "Partnership": "partnerskab",
    "Corporation": "selskab",
    "Non-profit": "non-profit",
    "Organization": "organisation",
    "Government": "regering",
    "1 year": "1 år",
    "2 years": "2 år",
    "3 years": "3 år",
    "4 years": "4 år",
    "5 years": "5 år",
    "6 years": "6 år",
    "7 years": "7 år",
    "8 years": "8 år",
    "9 years": "9 år",
    "10 years": "10 år",
    "Date Signed*": "Underskriftsdato*",
    "Client existant": "Eksisterende klient",
    "New Client": "Ny klient",
    "Other": "Andet",
    "Submit": "Indsend",
    "Application Received": "Ansøgning modtaget",
    "We received your loan application request;": "Vi har modtaget din låneansøgning;",
    "we'll be in touch shortly!": "vi kontakter dig snart!"
  },
  ro: {
    "Commercial Loan Application Form": "Formular de Cerere pentru Împrumut Comercial",
    "Applicant Information": "Informații despre Solicitant",
    "Name": "Nume",
    "First Name": "Prenume",
    "Last Name": "Nume de Familie",
    "Address*": "Adresă*",
    "Street Address": "Adresă Stradală",
    "Street Address Line 2": "Adresă Stradală Linia 2",
    "City": "Oraș",
    "State / Province": "Stat / Provincie",
    "Postal / Zip Code": "Cod Poștal / ZIP",
    "Applicant Status*": "Stare Solicitant*",
    "New Client": "Client Nou",
    "Existing Client": "Client Există",
    "Other": "Altele",
    "Job / Occupation": "Loc de Muncă / Ocupație",
    "Job Classification": "Clasificare Ocupațională",
    "Please Select": "Vă Rugăm Selectați",
    "Email Address": "Adresă de Email",
    "example@example.com": "exemplu@exemplu.com",
    "Loan Information": "Informații Împrumut",
    "Loan Amount*": "Suma Împrumutului*",
    "Loan/Credit Term*": "Termen Împrumut / Credit*",
    "Type of Loan Facility*": "Tipul de Facilitate de Împrumut*",
    "Overdraft": "Descoperit",
    "Commercial Property": "Proprietate Comercială",
    "Industrial Property": "Proprietate Industrială",
    "Micro Loans": "Microîmprumuturi",
    "Revolving Credit": "Credit Rotativ",
    "Equipment Financing": "Finanțare Echipament",
    "Other": "Altele",
    "Purpose of your Loan*": "Scopul Împrumutului Tău*",
    "ID card front*": "Carte de Identitate Față*",
    "Browse Files": "Răsfoiește Fișiere",
    "No file chosen": "Niciun fișier selectat",
    "ID card back*": "Carte de Identitate Spate*",
    "I/We hereby affirm this application for loan or credit as specified above in this application form, on behalf of the business applicant. The information specified above provided are true and correct to the best of my/our knowledge and with no intention to commit acts of misrepresentation. No addition or omission has been made which may lead to acts of fraud or any form of impropriety.": "Prin prezenta, afirmăm această cerere de împrumut sau credit așa cum este specificată mai sus în acest formular de cerere, în numele solicitantului comercial. Informațiile specificate mai sus sunt adevărate și corecte în cunoștința noastră și fără intenția de a comite acte de vătămare. Nu s-a făcut nicio adăugare sau omisiune care ar putea duce la acte de fraudă sau orice formă de impropriu.",
    "This field is required.": "Acest câmp este obligatoriu.",
    "I/We agree that the Lender is authorized to conduct any form of investigation in order to verify and confirm our declarations and requests, including, but not limited to conduct any investigation of my/our credit standing.": "Sunt de acord că creditorul este autorizat să efectueze orice formă de investigație pentru a verifica și confirma declarațiile și solicitările noastre, inclusiv, dar fără a se limita la, efectuarea oricărei investigații asupra situației noastre de credit. Cu condiția de a primi notificare prealabilă, creditorul poate divulga informații financiare despre contul nostru oricărui alt creditor sau părți interesate la informațiile care pot fi necesare pentru divulgare în legătură cu investigația de credit.",
    "Provided that with given notice, Lender may disclose financial information of our account to any another lender or parties interested to the information which may be needed for disclosure in relevance to credit investigation.": "Cu condiția ca, cu notificare prealabilă, Creditorul poate dezvălui informații financiare despre contul nostru oricărui alt creditor sau părți interesate de informație, care ar putea fi necesare pentru dezvăluire în legătură cu o investigație de credit.",
    "Signature": "Semnătură",
    "Proprietor": "proprietar",
    "Partnership": "parteneriat",
    "Corporation": "corporație",
    "Non-profit": "organizație non-profit",
    "Organization": "organizație",
    "Government": "guvern",
    "1 year": "1 an",
    "2 years": "2 ani",
    "3 years": "3 ani",
    "4 years": "4 ani",
    "5 years": "5 ani",
    "6 years": "6 ani",
    "7 years": "7 ani",
    "8 years": "8 ani",
    "9 years": "9 ani",
    "10 years": "10 ani",
    "Date Signed*": "Data semnării*",
    "Client existant": "Client existent",
    "New Client": "Client nou",
    "Other": "Altul",
    "Submit": "Trimite",
    "Application Received": "Aplicatie primita",
    "We received your loan application request;": "Am primit cererea ta de împrumut;",
    "we'll be in touch shortly!": "vom fi în contact în curând!"
  },
  
  
  };
  
const translation = translations[language] || translations.en; // Default to English
		    return translation[text] || text;
		}
		
		
		
		
		document.addEventListener("DOMContentLoaded", function() {
		    // Define the IDs of the elements to translate
		    const elementsToTranslate = ["header_1", "label_45",  "sublabel_45_first", "label_6", "label_12", "sublabel_12_addr_line2", "sublabel_12_addr_line1", "sublabel_12_city", "sublabel_12_postal", "label_25", "label_10", "label_32", "label_35", "label_38" , "label_36" , "label_43", "bh1" , "label_8" , "sublabel_12_state" , "label_52" , "label_24" , "id_32" , "label_53" , "label_34" , "form-pagebreak-next_54" , "label_input_38_1" , "label_input_38_2" , "label_input_38_3", "label_input_38_5", "label_input_38_6", "label_input_38_7", "label_input_25_1", "label_input_25_2", "sublabel_45_last", "label_input_25_0", "signclr", "label_35", "label_35", "label_35"   ]; 
			const placeHolder = ["ps","p1","p2","p3","p4","p5","p6","p7","bh1","bh2","psy","1y","2y","3y","4y","5y","6y","7y","8y","9y","10y","form-pagebreak-next_54","label_32","tc1","tc2","tc3","mess","mess2","scs"];
		     
		    // Translate each element based on the user's language
		    elementsToTranslate.forEach(elementId => {
		        const element = document.getElementById(elementId);
		        if (element) {
		        	
		            element.innerText = translate(element.innerText, userLanguage); 
		        }
		        
		        
		        
		  
		        placeHolder.forEach(placeHolderId => {
		        const PlaceH = document.getElementById(placeHolderId);
		        if (PlaceH) {
		        	//console.log(translate(PlaceH.textContent, userLanguage));
		            PlaceH.textContent = translate(PlaceH.textContent, userLanguage);  
		        	}
		        }); 
		        
		        document.getElementById('form-pagebreak-next_54').addEventListener("click", function() {
		        console.log('subbut-clicked');
		        
			
		});
		    });
		});
		
		